[package]
name = "uart-rs-test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.89"
serialport = "4.5.1"
bincode = "1.3.3"
zerocopy = { version = "0.7.35", features = ["derive"] }
cobs-rs = "1.1.2"
