version: '3'
services:
  uart-rs-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Working
      - ..:/workspaces/uart-rs-test:cached
      # device access
      - /dev:/dev
    working_dir: /workspaces/uart-rs-test
    tty: true
    command: sleep inf
    # device access
    privileged: true
